# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6f2f83b4d85ded8bf964a103f56d71bfb51a4aafa1d9c6ea10ffabafddd73c69d95763b87dfb608a9ee8bb7884a05b5b575f2c12433da054c5c7b05e5b05989e

test:
  secret_key_base: f556dfc8845185ab388245b2191b3ef88165efca33c55356e8bcfe3de486d0d3d6fff3637aa233b11d4caa890df0b0b60f995120089441b3e44c8675abbbaadd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
